# Sparse Matrices

In [ ]:
"""Matrices that contain mostly zero values are called sparse,distinct from matrices where most
of the values are non-zero, called dense"""

In [ ]:
"""Large sparse matrices are common in general and
especially in applied machine learning, such as in data that contains counts, data encodings
that map categories to counts, and even in whole subfields of machine learning such as natural
language processing. It is computationally expensive to represent and work with sparse matrices
as though they are dense, and much improvement in performance can be achieved by using
representations and operations that specifically handle the matrix sparsity."""

"""
1- That sparse matrices contain mostly zero values and are distinct from dense matrices.
2- The myriad of areas where you are likely to encounter sparse matrices in data, data
preparation, and sub-fields of machine learning.
3- That there are many efficient ways to store and work with sparse matrices and SciPy
provides implementations that you can use directly.
"""

"""
1. Sparse Matrix
2. Problems with Sparsity
3. Sparse Matrices in Machine Learning
4. Working with Sparse Matrices
5. Sparse Matrices in Python
"""

In [ ]:
# Sparse Matrix
"""A sparse matrix is a matrix that is comprised of mostly zero values. Sparse matrices are distinct
from matrices with mostly non-zero values, which are referred to as dense matrices.
"""
"""
The sparsity of a matrix can be quantified with a score, which is the number of zero values
in the matrix divided by the total number of elements in the matrix.

sparsity =count of non-zero elements / total elements

"""

"""Below is an example of a small 3 × 6 sparse matrix.
A = (1 0 0 1 0 0
    0 0 2 0 0 1
    0 0 0 2 0 0)
    
The example has 13 zero values of the 18 elements in the matrix, giving this matrix a sparsity
score of 0.722 or about 72%.
"""
"""Space Complexity"""

"""Very large matrices require a lot of memory, and some very large matrices that we wish to work
with are sparse.
In practice, most large matrices are sparse — almost all entries are zeros"""

"""
An example of a very large matrix that is too large to be stored in memory is a link matrix
that shows the links from one website to another. An example of a smaller sparse matrix might
be a word or term occurrence matrix for words in one book against all known words in English.
In both cases, the matrix contained is sparse with many more zero values than data values. The
problem with representing these sparse matrices as dense matrices is that memory is required
and must be allocated for each 32-bit or even 64-bit zero value in the matrix. This is clearly a
waste of memory resources as those zero values do not contain any information
"""

# Time Complexity 

"""Assuming a very large sparse matrix can be fit into memory, we will want to perform operations
on this matrix. Simply, if the matrix contains mostly zero-values, i.e. no data, then performing
operations across this matrix may take a long time where the bulk of the computation performed
will involve adding or multiplying zero values together."""

"""It is wasteful to use general methods of linear algebra on such problems, because
most of the O(N3) arithmetic operations devoted to solving the set of equations or
inverting the matrix involve zero operands"""

"""
This is a problem of increased time complexity of matrix operations that increases with the
size of the matrix. This problem is compounded when we consider that even trivial machine
learning methods may require many operations on each row, column, or even across the entire
matrix, resulting in vastly longer execution times.

"""

# Data Preparation

In [ ]:
"""
Sparse matrices come up in encoding schemes used in the preparation of data. Three common
examples include:
ˆ One hot encoding, used to represent categorical data as sparse binary vectors.
ˆ Count encoding, used to represent the frequency of words in a vocabulary for a document
ˆ TF-IDF encoding, used to represent normalized word frequency scores in a vocabulary.
"""

# Working with Sparse Matrices
"""
Areas of Study
Some areas of study within machine learning must develop specialized methods to address
sparsity directly as the input data is almost always sparse. Three examples include:
ˆ Natural language processing for working with documents of text.
ˆ Recommender systems for working with product usage within a catalog.
ˆ Computer vision when working with images that contain lots of black pixels.

If there are 100,000 words in the language model, then the feature vector has length
100,000, but for a short email message almost all the features will have count zero.
"""


# Working with Sparse Matrices

In [ ]:
"""
The solution to representing and working with sparse matrices is to use an alternate data
structure to represent the sparse data. The zero values can be ignored and only the data or
non-zero values in the sparse matrix need to be stored or acted upon. There are multiple data
structures that can be used to efficiently construct a sparse matrix; three common examples are
listed below.
ˆ Dictionary of Keys. A dictionary is used where a row and column index is mapped to
a value.
ˆ List of Lists. Each row of the matrix is stored as a list, with each sublist containing the
column index and the value.
ˆ Coordinate List. A list of tuples is stored with each tuple containing the row index,
column index, and the value
"""

"""
There are also data structures that are more suitable for performing efficient operations; two
commonly used examples are listed below.
ˆ Compressed Sparse Row. The sparse matrix is represented using three one-dimensional
arrays for the non-zero values, the extents of the rows, and the column indexes.
ˆ Compressed Sparse Column. The same as the Compressed Sparse Row method except
the column indices are compressed and read first before the row indices.
"""

# Sparse Matrices in Python

In [2]:
"""
SciPy provides tools for creating sparse matrices using multiple data structures, as well as
tools for converting a dense matrix to a sparse matrix
"""

"""
A dense matrix stored in a NumPy array can be converted into a sparse matrix using the
CSR representation by calling the csr matrix() function. In the example below, we define a
3×6 sparse matrix as a dense array (e.g. an ndarray), convert it to a CSR sparse representation,
and then convert it back to a dense array by calling the todense() function.
"""

## Example of converting between dense and sparse matrices.

# sparse matrix
from numpy import array
from scipy.sparse import csr_matrix
# create dense matrix
A = array([
[1, 0, 0, 1, 0, 0],
[0, 0, 2, 0, 0, 1],
[0, 0, 0, 2, 0, 0]])
print(A)
# convert to sparse matrix (CSR method)
S = csr_matrix(A)
print(S)
# reconstruct dense matrix
B = S.todense()
print(B)


[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]
  (0, 0)	1
  (0, 3)	1
  (1, 2)	2
  (1, 5)	1
  (2, 3)	2
[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]


In [3]:
# sparsity = 1.0 - count_nonzero(A) / A.size

# sparsity calculation
from numpy import array
from numpy import count_nonzero
# create dense matrix
A = array([
[1, 0, 0, 1, 0, 0],
[0, 0, 2, 0, 0, 1],
[0, 0, 0, 2, 0, 0]])
print(A)
# calculate sparsity
sparsity = 1.0 - count_nonzero(A) / A.size
print(sparsity)

[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]
0.7222222222222222
