# Matrix Operations

In [ ]:
"""Matrix operations are used in the description of many machine learning algorithms. Some
operations can be used directly to solve key equations, whereas others provide useful shorthand
or foundation in the description and the use of more complex matrix operations."""

"""
1. Transpose
2. Inverse
3. Trace
4. Determinant
5. Rank
"""

In [2]:
# Transpose
"""A defined matrix can be transposed, which creates a new matrix with the number of columns
and rows flipped. This is denoted by the superscript T next to the matrix AT
.
C = AT(T is superscript)"""

"""
A =(1 2
    3 4
    5 6)

AT(T is superscript) =(1 3 5
    2 4 6)

"""
"""The operation has no effect if the matrix is symmetrical, e.g. has the same number of
columns and rows and the same values at the same locations on both sides of the invisible
diagonal line"""

# transpose matrix
from numpy import array
# define matrix
A = array([
[1, 2],
[3, 4],
[5, 6]])
print(A)
# calculate transpose
C = A.T
print(C)

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [3]:
# Inverse

"""Matrix inversion is a process that finds another matrix that when multiplied with the matrix,
results in an identity matrix. Given a matrix A, find matrix B, such that AB = I
n or BA = I
n
.
AB = BA = In( n is superscript)"""
# invert matrix
from numpy import array
from numpy.linalg import inv
# define matrix
A = array([
[1.0, 2.0],
[3.0, 4.0]])
print(A)
# invert matrix
B = inv(A)
print(B)
# multiply A and B
I = A.dot(B)
print(I)

[[1. 2.]
 [3. 4.]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [4]:
# Trace
"""A trace of a square matrix is the sum of the values on the main diagonal of the matrix (top-left
to bottom-right)"""
# matrix trace
from numpy import array
from numpy import trace
# define matrix
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(A)
# calculate trace
B = trace(A)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
15


In [5]:
# Determinant
"""The determinant of a square matrix is a scalar representation of the volume of the matrix."""
# matrix determinant
from numpy import array
from numpy.linalg import det
# define matrix
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(A)
# calculate determinant
B = det(A)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
0.0


In [6]:
# Rank
"""The rank of a matrix is the estimate of the number of linearly independent rows or columns in
a matrix. The rank of a matrix M is often denoted as the function rank().
rank(A)"""
# vector rank
from numpy import array
from numpy.linalg import matrix_rank
# rank
v1 = array([1,2,3])
print(v1)
vr1 = matrix_rank(v1)
print(vr1)
# zero rank
v2 = array([0,0,0,0,0])
print(v2)
vr2 = matrix_rank(v2)
print(vr2)

[1 2 3]
1
[0 0 0 0 0]
0


In [7]:
"""The next example makes it clear that the rank is not the number of dimensions of the
matrix, but the number of linearly independent directions. Three examples of a 2 × 2 matrix
are provided demonstrating matrices with rank 0, 1 and 2"""
# matrix rank
from numpy import array
from numpy.linalg import matrix_rank
# rank 0
M0 = array([
[0,0],
[0,0]])
print(M0)
mr0 = matrix_rank(M0)
print(mr0)
# rank 1
M1 = array([
[1,2],
[1,2]])
print(M1)
mr1 = matrix_rank(M1)
print(mr1)
# rank 2
M2 = array([
[1,2],
[3,4]])
print(M2)
mr2 = matrix_rank(M2)
print(mr2)


[[0 0]
 [0 0]]
0
[[1 2]
 [1 2]]
1
[[1 2]
 [3 4]]
2
