# Factorization

### Matrix Decompositions

In [ ]:
"""A matrix decomposition is a way of reducing a matrix into its constituent parts. It is an
approach that can simplify more complex matrix operations that can be performed on the
decomposed matrix rather than on the original matrix itself. A common analogy for matrix
decomposition is the factoring of numbers. 
such as the factoring of 10 into 2 × 5. For this reason,
matrix decomposition is also called matrix factorization. """


"""there are a range of different matrix decomposition techniques. """
1- LU matrix decomposition 
2- QR matrix decomposition

### LU Decomposition

In [ ]:
"""The LU decomposition is for square matrices and decomposes a matrix into L and U components."""

A = L · U

Or, without the dot notation.

A = LU

Where A is the square matrix that we wish to decompose, L is the lower triangle matrix
and U is the upper triangle matrix.

In [ ]:
"""The LU decomposition is found using an iterative numerical process and can fail for those
matrices that cannot be decomposed or decomposed easily. A variation of this decomposition
that is numerically more stable to solve in practice is called the LUP decomposition, or the LU
decomposition with partial pivoting.

A = L · U · P

The LU decomposition can be implemented in Python with the lu() function. More
specifically, this function calculates an LPU decomposition. The example below first defines a
3×3 square matrix. The LU decomposition is calculated, then the original matrix is reconstructed
from the components.
"""

In [2]:
# LU decomposition
from numpy import array
from scipy.linalg import lu
# define a square matrix
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(A)
# factorize
P, L, U = lu(A)
print(P)
print("----------")
print(L)
print("----------")
print(U)
print("----------")
# reconstruct
"""Running the example first prints the defined 3 × 3 matrix, then the P, L, and U components
of the decomposition, then finally the original matrix is reconstructed."""
B = P.dot(L).dot(U)
print(B)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
----------
[[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]
----------
[[7.         8.         9.        ]
 [0.         0.85714286 1.71428571]
 [0.         0.         0.        ]]
----------
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


### QR Decomposition

In [ ]:
"""The QR decomposition is for n × m matrices (not limited to square matrices) and decomposes
a matrix into Q and R components

A = Q · R

Or, without the dot notation.

A = QR

Where A is the matrix that we wish to decompose, Q a matrix with the size m × m, and R is
an upper triangle matrix with the size m × n
"""

In [ ]:
"""The QR decomposition is found using an iterative
numerical method that can fail for those matrices that cannot be decomposed, or decomposed
easily. Like the LU decomposition, the QR decomposition is often used to solve systems of
linear equations, although is not limited to square matrices

We can change this to return the expected sizes of m × m for Q and m × n for
R by specifying the mode argument as ‘complete’, although this is not required for most
applications. The example below defines a 3 × 2 matrix, calculates the QR decomposition, then
reconstructs the original matrix from the decomposed elements
"""

In [3]:
# QR decomposition
from numpy import array
from numpy.linalg import qr
# define rectangular matrix
A = array([
[1, 2],
[3, 4],
[5, 6]])
print(A)
# factorize
Q, R = qr(A, 'complete')
print(Q)
print(R)
# reconstruct
"""Running the example first prints the defined 3 × 2 matrix, then the Q and R elements, then
finally the reconstructed matrix that matches what we started with."""

B = Q.dot(R)
print(B)

[[1 2]
 [3 4]
 [5 6]]
[[-0.16903085  0.89708523  0.40824829]
 [-0.50709255  0.27602622 -0.81649658]
 [-0.84515425 -0.34503278  0.40824829]]
[[-5.91607978 -7.43735744]
 [ 0.          0.82807867]
 [ 0.          0.        ]]
[[1. 2.]
 [3. 4.]
 [5. 6.]]


### Cholesky Decomposition

In [ ]:
"""The Cholesky decomposition is for square symmetric matrices where all values are greater than
zero, so-called positive definite matrices. For our interests in machine learning, we will focus on
the Cholesky decomposition for real-valued matrices and ignore the cases when working with
complex numbers

The decomposition is defined as follows:

A = L · LT(T is superscript)

Where A is the matrix being decomposed, L is the lower triangular matrix and LT(T is super script)
is the transpose of L. The decompose can also be written as the product of the upper triangular
matrix, for example:

"""

In [4]:
"""The Cholesky decomposition can be implemented in NumPy by calling the cholesky()
function. The function only returns L as we can easily access the L transpose as needed. The
example below defines a 3×3 symmetric and positive definite matrix and calculates the Cholesky
decomposition, then the original matrix is reconstructed."""

# Cholesky decomposition
from numpy import array
from numpy.linalg import cholesky
# define symmetrical matrix
A = array([
[2, 1, 1],
[1, 2, 1],
[1, 1, 2]])
print(A)
# factorize
L = cholesky(A)
print(L)
# reconstruct
B = L.dot(L.T)
print(B)


[[2 1 1]
 [1 2 1]
 [1 1 2]]
[[1.41421356 0.         0.        ]
 [0.70710678 1.22474487 0.        ]
 [0.70710678 0.40824829 1.15470054]]
[[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]
