# Types of Matrices

In [ ]:
"""
A lot of linear algebra is concerned with operations on vectors and matrices, and there are many
different types of matrices. There are a few types of matrices that you may encounter again and
again when getting started in linear algebra, particularity the parts of linear algebra relevant to
machine learning. In this tutorial, you will discover a suite of different types of matrices from
the field of linear algebra that you may encounter in machine learning. After completing this
tutorial, you will know:
ˆ Square, symmetric, triangular, and diagonal matrices that are much as their names suggest.
ˆ Identity matrices that are all zero values except along the main diagonal where the values
are 1.
ˆ Orthogonal matrices that generalize the idea of perpendicular vectors and have useful
computational properties

1. Square Matrix
2. Symmetric Matrix
3. Triangular Matrix
4. Diagonal Matrix
5. Identity Matrix
6. Orthogonal Matrix
"""

In [ ]:
# Square Matrix

"""
A square matrix is a matrix where the number of rows (n) is equivalent to the number of
columns (m).

n ≡ m 

The square matrix is contrasted with the rectangular matrix where the number of rows and
columns are not equal. Given that the number of rows and columns match, the dimensions are
usually denoted as n, e.g. n × n. The size of the matrix is called the order, so an order 4 square
matrix is 4 × 4. The vector of values along the diagonal of the matrix from the top left to the
bottom right is called the main diagonal. Below is an example of an order 3 square matrix.

M = (1 2 3
    1 2 3
    1 2 3)

"""
"""Square matrices are readily added and multiplied together and are the basis of many simple
linear transformations, such as rotations (as in the rotations of images)"""

In [ ]:
# Symmetric Matrix

"""A symmetric matrix is a type of square matrix where the top-right triangle is the same as the
bottom-left triangle.
"""
"""To be symmetric, the axis of symmetry is always the main diagonal of the matrix, from the
top left to the bottom right. Below is an example of a 5 × 5 symmetric matrix."""

"""M =  (1 2 3 4 5
        2 1 2 3 4
        3 2 1 2 3
        4 3 2 1 2
        5 4 3 2 1)"""

"""A symmetric matrix is always square and equal to its own transpose"""

In [1]:
# Triangular Matrix

"""A triangular matrix is a type of square matrix that has all values in the upper-right or lower-left
of the matrix with the remaining elements filled with zero values. A triangular matrix with
values only above the main diagonal is called an upper triangular matrix. Whereas, a triangular
matrix with values only below the main diagonal is called a lower triangular matrix. Below is
an example of a 3 × 3 upper triangular matrix.
"""
# triangular matrices
from numpy import array
from numpy import tril
from numpy import triu
# define square matrix
M = array([
[1, 2, 3],
[1, 2, 3],
[1, 2, 3]])
print(M)
# lower triangular matrix
lower = tril(M)
print(lower)
# upper triangular matrix
upper = triu(M)
print(upper)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 0 0]
 [1 2 0]
 [1 2 3]]
[[1 2 3]
 [0 2 3]
 [0 0 3]]


In [2]:
#  Diagonal Matrix

"""A diagonal matrix is one where values outside of the main diagonal have a zero value, where the
main diagonal is taken from the top left of the matrix to the bottom right. A diagonal matrix
is often denoted with the variable D and may be represented as a full matrix or as a vector of
values on the main diagonal."""

"""Diagonal matrices consist mostly of zeros and have non-zero entries only along the
main diagonal."""
# diagonal matrix
from numpy import array
from numpy import diag
# define square matrix
M = array([
[1, 2, 3],
[1, 2, 3],
[1, 2, 3]])
print(M)
# extract diagonal vector
d = diag(M)
print(d)
# create diagonal matrix from vector
D = diag(d)
print(D)


[[1 2 3]
 [1 2 3]
 [1 2 3]]
[1 2 3]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [3]:
# Identity Matrix
"""An identity matrix is a square matrix that does not change a vector when multiplied. The
values of an identity matrix are known. All of the scalar values along the main diagonal (top-left
to bottom-right) have the value one, while all other values are zero."""

# identity matrix
from numpy import identity
I = identity(3)
print(I)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
# Orthogonal Matrix

"""Two vectors are orthogonal when their dot product equals zero. The length of each vector is 1
then the vectors are called orthonormal because they are both orthogonal and normalized.
v · w = 0 
"""
# orthogonal matrix
from numpy import array
from numpy.linalg import inv
# define orthogonal matrix
Q = array([
[1, 0],
[0, -1]])
print(Q)
# inverse equivalence
V = inv(Q)
print(Q.T)
print(V)
# identity equivalence
I = Q.dot(Q.T)
print(I)

[[ 1  0]
 [ 0 -1]]
[[ 1  0]
 [ 0 -1]]
[[ 1.  0.]
 [-0. -1.]]
[[1 0]
 [0 1]]
