# Singular Value Decomposition

In [ ]:
"""Matrix decomposition, also known as matrix factorization, involves describing a given matrix
using its constituent elements. Perhaps the most known and widely used matrix decomposition
method is the Singular-Value Decomposition, or SVD. All matrices have an SVD, which makes
it more stable than other methods, such as the eigendecomposition. As such, it is often used
in a wide array of applications including compressing, denoising, and data reduction

1. What is the Singular-Value Decomposition
2. Calculate Singular-Value Decomposition
3. Reconstruct Matrix
4. Pseudoinverse
5. Dimensionality Reduction
"""

### What is the Singular-Value Decomposition

In [ ]:
"""The Singular-Value Decomposition, or SVD for short, is a matrix decomposition method for
reducing a matrix to its constituent parts in order to make certain subsequent matrix calculations
simpler. For the case of simplicity we will focus on the SVD for real-valued matrices and ignore
the case for complex numbers"""

A = U · Σ · VT(T is superscript)

Where A is the real n × m matrix that we wish to decompose, U is an m × m matrix, Σ
represented by the uppercase Greek letter sigma) is an m × n diagonal matrix, and VT
is the V transpose of an n × n matrix where T is a superscript

The singular value decomposition (SVD) provides another way to factorize a matrix,
into singular vectors and singular values. The SVD allows us to discover some of
the same kind of information as the eigendecomposition. However, the SVD is more
generally applicable.

### Uses of SVD
The SVD is used widely both in the calculation of other matrix operations, such as matrix
inverse, but also as a data reduction method in machine learning. SVD can also be used in least
squares linear regression, image compression, and denoising data

### Calculate Singular-Value Decomposition

In [1]:
"""The SVD can be calculated by calling the svd() function. The function takes a matrix and
returns the U, Σ and VT(T is super script)
elements. The Σ diagonal matrix is returned as a vector of singular
values. The V matrix is returned in a transposed form, e.g. VT(T is super script)
. The example below defines a 3 × 2 matrix and calculates the singular-value decomposition."""

# singular-value decomposition
from numpy import array
from scipy.linalg import svd
# define a matrix
A = array([
[1, 2],
[3, 4],
[5, 6]])
print(A)
# factorize
U, s, V = svd(A)
print(U)
print(s)
print(V)

"""Running the example first prints the defined 3×2 matrix, then the 3×3 U matrix, 2 element
Σ vector, and 2 × 2 VT(T is superscript) matrix elements calculated from the decomposition"""

[[1 2]
 [3 4]
 [5 6]]
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
[9.52551809 0.51430058]
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


### Reconstruct Matrix

In [ ]:
"""The original matrix can be reconstructed from the U, Σ, and VT
elements. The U, s, and V
elements returned from the svd() cannot be multiplied directly. The s vector must be converted
into a diagonal matrix using the diag() function. By default, this function will create a square
matrix that is m × m, relative to our original matrix. This causes a problem as the size of
the matrices do not fit the rules of matrix multiplication, where the number of columns in a
matrix must match the number of rows in the subsequent matrix. After creating the square Σ
diagonal matrix, the sizes of the matrices are relative to the original n × m matrix that we are
decomposing, as follows:
U(m × m) · Σ(m × m) · VT(T is superscript)(n × n)"""

U(m × m) · Σ(m × n) · VT(n × n)

Where T is super script of V

In [2]:
## Sample output from reconstructing a rectangular matrix from a SVD.
# reconstruct rectangular matrix from svd
from numpy import array
from numpy import diag
from numpy import zeros
from scipy.linalg import svd
# define matrix
A = array([
[1, 2],
[3, 4],
[5, 6]])
print(A)
# factorize
U, s, V = svd(A)
# create m x n Sigma matrix
Sigma = zeros((A.shape[0], A.shape[1]))
# populate Sigma with n x n diagonal matrix
Sigma[:A.shape[1], :A.shape[1]] = diag(s)
# reconstruct matrix
B = U.dot(Sigma.dot(V))
print(B)

[[1 2]
 [3 4]
 [5 6]]
[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [3]:
"""The above complication with the Σ diagonal only exists with the case where m and n are
not equal. The diagonal matrix can be used directly when reconstructing a square matrix, as
follows."""

# reconstruct square matrix from svd
from numpy import array
from numpy import diag
from scipy.linalg import svd
# define matrix
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(A)
# factorize
U, s, V = svd(A)
# create n x n Sigma matrix
Sigma = diag(s)
# reconstruct matrix
B = U.dot(Sigma.dot(V))
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


### Pseudoinverse


In [ ]:
"""The pseudoinverse is the generalization of the matrix inverse for square matrices to rectangular
matrices where the number of rows and columns are not equal. It is also called the Moore-Penrose
Inverse after two independent discoverers of the method or the Generalized Inverse."""

"""Matrix inversion is not defined for matrices that are not square. [...] When A has
more columns than rows, then solving a linear equation using the pseudoinverse
provides one of the many possible solutions.
— Page 46, Deep Learning, 2016."""


"""The pseudoinverse is denoted as A+, where A is the matrix that is being inverted and + is a
superscript. The pseudoinverse is calculated using the singular value decomposition of A:
"""

"""A+ = V · D+ · UT"""
where +, T is super script

"""A = U · Σ · VT"""

where T is super script

"""The D+ can be calculated by creating a diagonal matrix from Σ, calculating the reciprocal
of each non-zero element in Σ, and taking the transpose if the original matrix was rectangular."""

"""Where + is super sccript"""

Σ =(s1,1 0 0
    0 s2,2 0
    0 0 s3,3)


D+ =  (1/s1,1  0        0
      0        1 1/s2,  2
      0        0        1/s3,3)


"""The pseudoinverse provides one way of solving the linear regression equation, specifically
when there are more rows than there are columns, which is often the case. NumPy provides the
function pinv() for calculating the pseudoinverse of a rectangular matrix. The example below
defines a 4 × 2 matrix and calculates the pseudoinverse."""


In [4]:
# pseudoinverse
from numpy import array
from numpy.linalg import pinv
# define matrix
A = array([
[0.1, 0.2],
[0.3, 0.4],
[0.5, 0.6],
[0.7, 0.8]])
print(A)
# calculate pseudoinverse
B = pinv(A)
print(B)


[[0.1 0.2]
 [0.3 0.4]
 [0.5 0.6]
 [0.7 0.8]]
[[-1.00000000e+01 -5.00000000e+00  1.28785871e-14  5.00000000e+00]
 [ 8.50000000e+00  4.50000000e+00  5.00000000e-01 -3.50000000e+00]]


In [ ]:
"""We can calculate the pseudoinverse manually via the SVD and compare the results to the
pinv() function. First we must calculate the SVD. Next we must calculate the reciprocal of
each value in the s array. Then the s array can be transformed into a diagonal matrix with an
added row of zeros to make it rectangular. Finally, we can calculate the pseudoinverse from the
elements. The specific implementation is:

A+ = VT· DT· UT

where +, T is super script
"""

In [5]:
# pseudoinverse via svd
from numpy import array
from numpy.linalg import svd
from numpy import zeros
from numpy import diag
# define matrix
A = array([
[0.1, 0.2],
[0.3, 0.4],
[0.5, 0.6],
[0.7, 0.8]])
print(A)
# factorize
U, s, V = svd(A)
# reciprocals of s
d = 1.0 / s
# create m x n D matrix
D = zeros(A.shape)
# populate D with n x n diagonal matrix
D[:A.shape[1], :A.shape[1]] = diag(d)
# calculate pseudoinverse
B = V.T.dot(D.T).dot(U.T)
print(B)


[[0.1 0.2]
 [0.3 0.4]
 [0.5 0.6]
 [0.7 0.8]]
[[-1.00000000e+01 -5.00000000e+00  1.28508315e-14  5.00000000e+00]
 [ 8.50000000e+00  4.50000000e+00  5.00000000e-01 -3.50000000e+00]]


### Dimensionality Reduction

In [ ]:
"""A popular application of SVD is for dimensionality reduction. Data with a large number of
features, such as more features (columns) than observations (rows) may be reduced to a smaller
subset of features that are most relevant to the prediction problem."""


"""The result is a matrix with
a lower rank that is said to approximate the original matrix. To do this we can perform an SVD
operation on the original data and select the top k largest singular values in Σ. These columns
can be selected from Σ and the rows selected from VT
. An approximate B of the original vector
A can then be reconstructed"""

"""B = U · Σk · VT

Where k is lower script and T is super script

In natural language processing, this approach can be used on matrices of word occurrences
or word frequencies in documents and is called Latent Semantic Analysis or Latent Semantic
Indexing

In practice, we can retain and work with a descriptive subset of the data called T.
This is a dense summary of the matrix or a projection

T = U · Σk
where k is lower script
"""

"""The example below demonstrates data reduction with the SVD. First a 3 × 10 matrix is
defined, with more columns than rows. The SVD is calculated and only the first two features
are selected. The elements are recombined to give an accurate reproduction of the original
matrix. Finally the transform is calculated two different ways"""

In [6]:
# data reduction with svd
from numpy import array
from numpy import diag
from numpy import zeros
from scipy.linalg import svd
# define matrix
A = array([
[1,2,3,4,5,6,7,8,9,10],
[11,12,13,14,15,16,17,18,19,20],
[21,22,23,24,25,26,27,28,29,30]])
print(A)
# factorize
U, s, V = svd(A)
# create m x n Sigma matrix
Sigma = zeros((A.shape[0], A.shape[1]))
# populate Sigma with n x n diagonal matrix
Sigma[:A.shape[0], :A.shape[0]] = diag(s)
# select
n_elements = 2
Sigma = Sigma[:, :n_elements]
V = V[:n_elements, :]
# reconstruct
B = U.dot(Sigma.dot(V))
print(B)
# transform
T = U.dot(Sigma)
print(T)
T = A.dot(V.T)
print(T)


[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]]
[[-18.52157747   6.47697214]
 [-49.81310011   1.91182038]
 [-81.10462276  -2.65333138]]
[[-18.52157747   6.47697214]
 [-49.81310011   1.91182038]
 [-81.10462276  -2.65333138]]


In [7]:
"""The scikit-learn provides a TruncatedSVD class that implements this capability directly. The
TruncatedSVD class can be created in which you must specify the number of desirable features
or components to select, e.g. 2. Once created, you can fit the transform (e.g. calculate VTk)
by calling the fit() function, then apply it to the original matrix by calling the transform()
function. The result is the transform of A called T above. The example below demonstrates the
TruncatedSVD class.
"""

### Sample output from calculating data reduction with the SVD in scikit-learn.
# svd data reduction in scikit-learn
from numpy import array
from sklearn.decomposition import TruncatedSVD
# define matrix
A = array([
[1,2,3,4,5,6,7,8,9,10],
[11,12,13,14,15,16,17,18,19,20],
[21,22,23,24,25,26,27,28,29,30]])
print(A)
# create transform
svd = TruncatedSVD(n_components=2)
# fit transform
svd.fit(A)
# apply transform
result = svd.transform(A)
print(result)
"""Running the example first prints the defined matrix, followed by the transformed version
of the matrix. We can see that the values match those calculated manually above, except for
the sign on some values. We can expect there to be some instability when it comes to the
sign given the nature of the calculations involved and the differences in the underlying libraries
and methods used. This instability of sign should not be a problem in practice as long as the
transform is trained for reuse.
"""

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[[18.52157747  6.47697214]
 [49.81310011  1.91182038]
 [81.10462276 -2.65333138]]
