# Tensors and Tensor Arithmetic

In [ ]:
"""
In deep learning it is common to see a lot of discussion around tensors as the cornerstone
data structure. Tensor even appears in name of Google’s flagship machine learning library:
TensorFlow. Tensors are a type of data structure used in linear algebra, and like vectors and
matrices, you can calculate arithmetic operations with tensors
"""

"""
you will know:
ˆ That tensors are a generalization of matrices and are represented using n-dimensional
arrays.
ˆ How to implement element-wise operations with tensors.
ˆ How to perform the tensor product.
"""

In [ ]:
"""
they are:
1. What are Tensors
2. Tensors in Python
3. Tensor Arithmetic
4. Tensor Product
"""

# What are Tensors

In [1]:
"""
A tensor is a generalization of vectors and matrices and is easily understood as a multidimensional
array
"""

"""
In the general case, an array of numbers arranged on a regular grid with a variable
number of axes is known as a tensor
"""


"""
A vector is a one-dimensional or first order tensor and a matrix is a two-dimensional or second
order tensor. Tensor notation is much like matrix notation with a capital letter representing a
tensor and lowercase letters with subscript integers representing scalar values within the tensor.
For example, below defines a 3 × 3 × 3 three-dimensional tensor T with dimensions index as
ti,j,k.

T =
    (t1,1,1 t1,2,1 t1,3,1
    t2,1,1 t2,2,1 t2,3,1
    t3,1,1 t3,2,1 t3,3,1),
                            (t1,1,2 t1,2,2 t1,3,2
                            t2,1,2 t2,2,2 t2,3,2
                            t3,1,2 t3,2,2 t3,3,2),
                                            (t1,1,3 t1,2,3 t1,3,3
                                            t2,1,3 t2,2,3 t2,3,3
                                            t3,1,3 t3,2,3 t3,3,3)

"""
## Example of creating a tensor.
## below defines a 3 × 3 × 3 tensor as a NumPy ndarray
# create tensor
from numpy import array
T = array([
[[1,2,3], [4,5,6], [7,8,9]],
[[11,12,13], [14,15,16], [17,18,19]],
[[21,22,23], [24,25,26], [27,28,29]]])
print(T.shape)
print(T)


(3, 3, 3)
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]


#  Tensor Arithmetic

In [7]:
# Tensor Addition
#check this link  for tensor addition image
# https://i.ibb.co/1LZcZZw/1.png
# tensor addition
from numpy import array
# define first tensor
A = array([
[[1,2,3], [4,5,6], [7,8,9]],
[[11,12,13], [14,15,16], [17,18,19]],
[[21,22,23], [24,25,26], [27,28,29]]])
# define second tensor
B = array([
[[1,2,3], [4,5,6], [7,8,9]],
[[11,12,13], [14,15,16], [17,18,19]],
[[21,22,23], [24,25,26], [27,28,29]]])
# add tensors
C = A + B
print(C)

[[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[22 24 26]
  [28 30 32]
  [34 36 38]]

 [[42 44 46]
  [48 50 52]
  [54 56 58]]]


In [8]:
# tensor subtraction
from numpy import array
# define first tensor
A = array([
[[1,2,3], [4,5,6], [7,8,9]],
[[11,12,13], [14,15,16], [17,18,19]],
[[21,22,23], [24,25,26], [27,28,29]]])
# define second tensor
B = array([
[[1,2,3], [4,5,6], [7,8,9]],
[[11,12,13], [14,15,16], [17,18,19]],
[[21,22,23], [24,25,26], [27,28,29]]])
# subtract tensors
C = A - B
print(C)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


In [9]:
# tensor Hadamard product
from numpy import array
# define first tensor
A = array([
[[1,2,3], [4,5,6], [7,8,9]],
[[11,12,13], [14,15,16], [17,18,19]],
[[21,22,23], [24,25,26], [27,28,29]]])
# define second tensor
B = array([
[[1,2,3], [4,5,6], [7,8,9]],
[[11,12,13], [14,15,16], [17,18,19]],
[[21,22,23], [24,25,26], [27,28,29]]])
# multiply tensors
C = A * B
print(C)

[[[  1   4   9]
  [ 16  25  36]
  [ 49  64  81]]

 [[121 144 169]
  [196 225 256]
  [289 324 361]]

 [[441 484 529]
  [576 625 676]
  [729 784 841]]]


In [11]:
# tensor division
from numpy import array
# define first tensor
A = array([
[[1,2,3], [4,5,6], [7,8,9]],
[[11,12,13], [14,15,16], [17,18,19]],
[[21,22,23], [24,25,26], [27,28,29]]])
# define second tensor
B = array([
[[1,2,3], [4,5,6], [7,8,9]],
[[11,12,13], [14,15,16], [17,18,19]],
[[21,22,23], [24,25,26], [27,28,29]]])
# divide tensors
C = A / B
print(C)


[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


# Tensor Product

In [12]:
"""
The tensor product operator is often denoted as a circle with a small x in the middle. We will
denote it here as ⊗.
"""
"""
a =(a1
    a2)

b =(b1
    b2)

C = a ⊗ b 

C = (a1 × (b1
           b2)
     a2 ×(b1
          b2) )  
         
C =(a1 × b1 a1 × b2
    a2 × b1 a2 × b2)

"""
# tensor product
from numpy import array
from numpy import tensordot
# define first vector
A = array([1,2])
# define second vector
B = array([3,4])
# calculate tensor product
C = tensordot(A, B, axes=0)
print(C)

[[3 4]
 [6 8]]
