In [ ]:
# Vector L1 Norm
"""The length of a vector can be calculated using the L
1 norm, where the 1 is a superscript of
the L. The notation for the L
1 norm of a vector is ||v||1, where 1 is a subscript. As such, this
length is sometimes called the taxicab norm or the Manhattan norm.
L1

(v) = ||v||1 
The L1 norm is calculated as the sum of the absolute vector values, where the absolute value
of a scalar uses the notation |a1|. In effect, the norm is a calculation of the Manhattan distance
from the origin of the vector space.

||v||1 = |a1| + |a2| + |a3| """



# Vector Norm

In [1]:
"""Calculating the size or length of a vector is often required either directly or as part of a broader
vector or vector-matrix operation. The length of the vector is referred to as the vector norm or
the vector’s magnitude.
"""
# vector L1 norm
from numpy import array
from numpy.linalg import norm
# define vector
a = array([1, 2, 3])
print(a)
# calculate norm
l1 = norm(a, 1)
print(l1)


[1 2 3]
6.0


#  Vector L2(2 is super script) Norm

In [2]:
"""The length of a vector can be calculated using the L
2 norm, where the 2 is a superscript of the
L. The notation for the L
2 norm of a vector is ||v||2 where 2 is a subscript.
L2
(v) = ||v||2 
The L2 norm calculates the distance of the vector coordinate from the origin of the vector
space. As such, it is also known as the Euclidean norm as it is calculated as the Euclidean
distance from the origin. The result is a positive distance value. The L
2 norm is calculated as
the square root of the sum of the squared vector values.

||v||2 = square root of (a1 Square + a2 square + a3 square)

The L2 norm of a vector can be calculated in NumPy using the norm() function with default
parameters.
"""
# vector L2 norm
from numpy import array
from numpy.linalg import norm
# define vector
a = array([1, 2, 3])
print(a)
# calculate norm
l2 = norm(a)
print(l2)

[1 2 3]
3.7416573867739413


# Vector Max Norm

In [3]:
"""
The max norm is calculated as returning the maximum value of the vector, hence the name.
||v||inf = max a1, a2, a3

"""
# vector max norm
from math import inf
from numpy import array
from numpy.linalg import norm
# define vector
a = array([1, 2, 3])
print(a)
# calculate norm
maxnorm = norm(a, inf)
print(maxnorm)

[1 2 3]
3.0


In [ ]:
"""
Max norm is also used as a regularization in machine learning, such as on neural network
weights, called max norm regularization
"""