# Matrices and Matrix Arithmetic

In [1]:
"""
Matrices are a foundational element of linear algebra. Matrices are used throughout the field of
machine learning in the description of algorithms and processes such as the input data variable
(X) when training an algorithm
"""

'\nMatrices are a foundational element of linear algebra. Matrices are used throughout the field of\nmachine learning in the description of algorithms and processes such as the input data variable\n(X) when training an algorithm\n'

In [2]:
"""
1. What is a Matrix
2. Defining a Matrix
3. Matrix Arithmetic
4. Matrix-Matrix Multiplication
5. Matrix-Vector Multiplication
6. Matrix-Scalar Multiplication
"""
# What is a Matrix
"""A matrix is a two-dimensional array of scalars with one or more columns and one or more rows.
A matrix is a two-dimensional array (a table) of numbers."""

"""
The notation for a matrix is often an uppercase letter, such as A, and entries are referred to
by their two-dimensional subscript of row (i) and column (j), such as ai,j . For example, we can
define a 3-row, 2-column matrix

A = ((a1,1, a1,2),(a2,1, a2,2),(a3,1, a3,2))
"""
# create matrix
from numpy import array
A = array([[1, 2, 3], [4, 5, 6]])
print(A)


[[1 2 3]
 [4 5 6]]


In [3]:
# matrix addition
from numpy import array
# define first matrix
A = array([
[1, 2, 3],
[4, 5, 6]])
print(A)
# define second matrix
B = array([
[1, 2, 3],
[4, 5, 6]])
print(B)
# add matrices
C = A + B
print(C)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]


In [4]:
# matrix subtraction
from numpy import array
# define first matrix
A = array([
[1, 2, 3],
[4, 5, 6]])
print(A)
# define second matrix
B = array([
[0.5, 0.5, 0.5],
[0.5, 0.5, 0.5]])
print(B)
# subtract matrices
C = A - B
print(C)

[[1 2 3]
 [4 5 6]]
[[0.5 0.5 0.5]
 [0.5 0.5 0.5]]
[[0.5 1.5 2.5]
 [3.5 4.5 5.5]]


In [5]:
# matrix Hadamard product
from numpy import array
# define first matrix
A = array([
[1, 2, 3],
[4, 5, 6]])
print(A)
# define second matrix
B = array([
[1, 2, 3],
[4, 5, 6]])
print(B)
# multiply matrices
C = A * B
print(C)


[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]


In [6]:
# matrix division
from numpy import array
# define first matrix
A = array([
[1, 2, 3],
[4, 5, 6]])
print(A)
# define second matrix
B = array([
[1, 2, 3],
[4, 5, 6]])
print(B)
# divide matrices
C = A / B
print(C)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1. 1. 1.]
 [1. 1. 1.]]


#  Matrix-Matrix Multiplication

In [8]:
"""
C[0, 0] = A[0, 0] × B[0, 0] + A[0, 1] × B[1, 0]
C[1, 0] = A[1, 0] × B[0, 0] + A[1, 1] × B[1, 0]
C[2, 0] = A[2, 0] × B[0, 0] + A[2, 1] × B[1, 0]
C[0, 1] = A[0, 0] × B[0, 1] + A[0, 1] × B[1, 1]
C[1, 1] = A[1, 0] × B[0, 1] + A[1, 1] × B[1, 1]
C[2, 1] = A[2, 0] × B[0, 1] + A[2, 1] × B[1, 1]
(9.21)
The matrix multiplication operation can be implemented in NumPy using the dot() function.
It can also be calculated using the newer @ operator, since Python version 3.5. The example
below demonstrates both methods.

"""

# Example of matrix-matrix dot product.
# matrix dot product
from numpy import array
# define first matrix
A = array([
[1, 2],
[3, 4],
[5, 6]])
print(A)
# define second matrix
B = array([
[1, 2],
[3, 4]])
print(B)
# multiply matrices
C = A.dot(B)
print(C)
# multiply matrices with @ operator
D = A @ B
print(D)

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]]
[[ 7 10]
 [15 22]
 [23 34]]
[[ 7 10]
 [15 22]
 [23 34]]


# Matrix-Vector Multiplication

In [9]:
"""
We can also represent this with array notation.
c[0] = A[0, 0] × v[0] + A[0, 1] × v[1]
c[1] = A[1, 0] × v[0] + A[1, 1] × v[1]
c[2] = A[2, 0] × v[0] + A[2, 1] × v[1]
(9.28)
The matrix-vector multiplication can be implemented in NumPy using the dot() function.
"""

# matrix-vector multiplication
from numpy import array
# define matrix
A = array([
[1, 2],
[3, 4],
[5, 6]])
print(A)
# define vector
B = array([0.5, 0.5])
print(B)
# multiply
C = A.dot(B)
print(C)

[[1 2]
 [3 4]
 [5 6]]
[0.5 0.5]
[1.5 3.5 5.5]


# Matrix-Scalar Multiplication

In [10]:
# C = A · b

"""
We can also represent this with array notation.
C[0, 0] = A[0, 0] × b
C[1, 0] = A[1, 0] × b
C[2, 0] = A[2, 0] × b
C[0, 1] = A[0, 1] × b
C[1, 1] = A[1, 1] × b
C[2, 1] = A[2, 1] × b

This can be implemented directly in NumPy with the multiplication operator.
"""

# matrix-scalar multiplication
from numpy import array
# define matrix
A = array([[1, 2], [3, 4], [5, 6]])
print(A)
# define scalar
b = 0.5
print(b)
# multiply
C = A * b
print(C)


[[1 2]
 [3 4]
 [5 6]]
0.5
[[0.5 1. ]
 [1.5 2. ]
 [2.5 3. ]]
