In [ ]:
# Array Broadcasting
"""Arrays with different sizes cannot be added, subtracted, or generally be used in arithmetic. A
way to overcome this is to duplicate the smaller array so that it has the dimensionality and
size as the larger array. This is called array broadcasting and is available in NumPy when
performing array arithmetic, which can greatly reduce and simplify your code"""

In [1]:
# broadcast scalar to one-dimensional array
from numpy import array
# define array
a = array([1, 2, 3])
print(a)
# define scalar
b = 2
print(b)
# broadcast
c = a + b
print(c)
"""  
Ci,j = Ai,j + bj

In other words, the vector b is added to each row of the matrix.
This shorthand eliminates the need to define a matrix with b copied into each row
before doing the addition. This implicit copying of b to many locations is called
broadcasting"""


[1 2 3]
2
[3 4 5]


In [ ]:
#  Scalar and Two-Dimensional Array
"""A scalar value can be used in arithmetic with a two-dimensional array. For example, we can
imagine a two-dimensional array A with 2 rows and 3 columns added to the scalar b.
A =
(a1,1 a1,2 a1,3
a2,1 a2,2 a2,3)

The scalar will need to be broadcast across each row of the two-dimensional array by
duplicating it 5 more times.
B =
(b1,1 b1,2 b1,3
b2,1 b2,2 b2,3)

The two two-dimensional arrays can then be added directly.
C = A + B
C =
(a1,1 + b1,1 a1,2 + b1,2 a1,3 + b1,3
 a2,1 + b2,1 a2,2 + b2,2 a2,3 + b2,3)
"""

In [2]:
# broadcast scalar to two-dimensional array
from numpy import array
# define array
A = array([
[1, 2, 3],
[1, 2, 3]])
print(A)
# define scalar
b = 2
print(b)
# broadcast
C = A + b
print(C)


[[1 2 3]
 [1 2 3]]
2
[[3 4 5]
 [3 4 5]]


In [4]:
# broadcast one-dimensional array to two-dimensional array
from numpy import array
# define two-dimensional array
A = array([
[1, 2, 3],
[1, 2, 3]])
print(A)
# define one-dimensional array
b = array([1, 2, 3])
print(b)
# broadcast
C = A + b
print("One-Dimensional and Two-Dimensional Arrays")
print(C) # g broadcasting, can only be performed when the shape of each dimension in the arrays are equal or one has the dimension size of 1


[[1 2 3]
 [1 2 3]]
[1 2 3]
One-Dimensional and Two-Dimensional Arrays
[[2 4 6]
 [2 4 6]]


In [5]:
# Broadcasting Error
# broadcasting error
from numpy import array
# define two-dimensional array
A = array([
[1, 2, 3],
[1, 2, 3]])
print(A.shape)
# define one-dimensional array
b = array([1, 2])
print(b.shape)
# attempt broadcast
C = A + b
print(C)


(2, 3)
(2,)


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 