# Matrices

In [ ]:
# Defining a Vector
"""Vectors are often represented using a lowercase character such as v; for example:
v = (v1, v2, v3) 
Where v1, v2, v3 are scalar values, often real values.
Vectors are also shown using a vertical representation or a column; for example:
v =(v1
    v2
    v3)
"""

In [1]:
# create a vector
from numpy import array
# define vector
v = array([1, 2, 3])
print(v)

[1 2 3]


In [2]:
# c = (a1 + b1, a2 + b2, a3 + b3)
"""c[0] = a[0] + b[0]
c[1] = a[1] + b[1]
c[2] = a[2] + b[2]
"""
# vector addition
from numpy import array
# define first vector
a = array([1, 2, 3])
print(a)
# define second vector
b = array([1, 2, 3])
print(b)
# add vectors
c = a + b
print(c)

[1 2 3]
[1 2 3]
[2 4 6]


In [3]:
# c = (a1 − b1, a2 − b2, a3 − b3)
# vector subtraction
from numpy import array
# define first vector
a = array([1, 2, 3])
print(a)
# define second vector
b = array([0.5, 0.5, 0.5])
print(b)
# subtract vectors
c = a - b
print(c)


[1 2 3]
[0.5 0.5 0.5]
[0.5 1.5 2.5]


In [4]:
# c = (a1 × b1, a2 × b2, a3 × b3)
# vector multiplication
from numpy import array
# define first vector
a = array([1, 2, 3])
print(a)
# define second vector
b = array([1, 2, 3])
print(b)
# multiply vectors
c = a * b
print(c)

[1 2 3]
[1 2 3]
[1 4 9]


In [5]:
"""
c[0] = a[0]/b[0]
c[1] = a[1]/b[1]
c[2] = a[2]/b[2]
"""
# vector division
from numpy import array
# define first vector
a = array([1, 2, 3])
print(a)
# define second vector
b = array([1, 2, 3])
print(b)
# divide vectors
c = a / b
print(c)


[1 2 3]
[1 2 3]
[1. 1. 1.]


# Vector Dot Product


In [6]:
# c = (a1 × b1 + a2 × b2 + a3 × b3)
# vector dot product
from numpy import array
# define first vector
a = array([1, 2, 3])
print(a)
# define second vector
b = array([1, 2, 3])
print(b)
# multiply vectors
c = a.dot(b)
print(c)

[1 2 3]
[1 2 3]
14


In [7]:
# Vector-Scalar Multiplication
"""
c = (s × v1, s × v2, s × v3)
c[0] = v[0] × s
c[1] = v[1] × s
c[2] = v[2] × s
"""
# vector-scalar multiplication
from numpy import array
# define vector
a = array([1, 2, 3])
print(a)
# define scalar
s = 0.5
print(s)
# multiplication
c = s * a
print(c)


[1 2 3]
0.5
[0.5 1.  1.5]
