In [1]:
# create array
from numpy import array
# create array
l = [1.0, 2.0, 3.0]
a = array(l)
# display array
print(a)
# display array shape
print(a.shape)
# display array data type
print(a.dtype)

[1. 2. 3.]
(3,)
float64


In [2]:
# create empty array
from numpy import empty
a = empty([3,3])
print(a)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 7.35169681e-321]
 [1.10343781e-311 1.10343781e-311 0.00000000e+000]]


In [3]:
# create zero array
from numpy import zeros
a = zeros([3,5])
print(a)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [4]:
# create one array
from numpy import ones
a = ones([5])
print(a)

[1. 1. 1. 1. 1.]


In [5]:
# Vertical Stack
"""Given two or more existing arrays, you can stack them vertically using the vstack() function.
For example, given two one-dimensional arrays, you can create a new two-dimensional array
with two rows by vertically stacking them. This is demonstrated in the example below."""
# create array with vstack
from numpy import array
from numpy import vstack
# create first array
a1 = array([1,2,3])
print(a1)
# create second array
a2 = array([4,5,6])
print(a2)
# vertical stack
a3 = vstack((a1, a2))
print(a3)
print(a3.shape)


[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]
(2, 3)


In [6]:
# Horizontal Stack
"""Given two or more existing arrays, you can stack them horizontally using the hstack() function.
For example, given two one-dimensional arrays, you can create a new one-dimensional array or
one row with the columns of the first and second arrays concatenated. This is demonstrated in
the example below."""
# create array with hstack
from numpy import array
from numpy import hstack
# create first array
a1 = array([1,2,3])
print(a1)
# create second array
a2 = array([4,5,6])
print(a2)
# create horizontal stack
a3 = hstack((a1, a2))
print(a3)
print(a3.shape)

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]
(6,)
