In [1]:
# One-Dimensional List to Array
# create one-dimensional array
from numpy import array
# list of data
data = [11, 22, 33, 44, 55]
# array of data
data = array(data)
print(data)
print(type(data))


[11 22 33 44 55]
<class 'numpy.ndarray'>


In [2]:
# Two-Dimensional List of Lists to Array
# create two-dimensional array
from numpy import array
# list of data
data = [[11, 22],
[33, 44],
[55, 66]]
# array of data
data = array(data)
print(data)
print(type(data))

[[11 22]
 [33 44]
 [55 66]]
<class 'numpy.ndarray'>


In [3]:
# One-Dimensional Indexing
# index a one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
# index data
print(data[0])
print(data[4])


11
55


In [4]:
# index array out of bounds
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
# index data
print(data[5])


IndexError: index 5 is out of bounds for axis 0 with size 5

In [5]:
"""One key difference is that you can use negative indexes to retrieve values offset from the end
of the array. For example, the index -1 refers to the last item in the array. The index -2 returns
the second last item all the way back to -5 for the first item in the current example"""
# negative array indexing
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
# index data
print(data[-1])
print(data[-5])


55
11


In [6]:
# Two-Dimensional Indexing



IndexError: too many indices for array

In [7]:
# index two-dimensional array
from numpy import array
# define array
data = array([
[11, 22],
[33, 44],
[55, 66]])
# index data
print(data[0,0])


11


In [8]:
"""If we are interested in all items in the first row, we could leave the second dimension index
empty, for example:"""

# index row of two-dimensional array
from numpy import array
# define array
data = array([
[11, 22],
[33, 44],
[55, 66]])
# index data
print(data[0,])


[11 22]


In [ ]:
# The slice extends from the from index and ends one item before the to index
 ### syntax
data[from:to]


In [9]:
#One-Dimensional Slicing
"""You can access all data in an array dimension by specifying the slice ‘:’ with no indexes."""
# slice a one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data[:])


[11 22 33 44 55]


In [10]:
"""The first item of the array can be sliced by specifying a slice that starts at index 0 and ends
at index 1 (one item before the to index)."""
# slice a subset of a one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data[0:1])


[11]


In [11]:
"""We can also use negative indexes in slices. For example, we can slice the last two items in
the list by starting the slice at -2 (the second last item) and not specifying a to index; that
takes the slice to the end of the dimension"""
# negative slicing of a one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data[-2:])


[44 55]


In [ ]:
# Two-Dimensional Slicing
"""It is common to split your loaded data into input variables (X) and the output variable (y). We
can do this by slicing all rows and all columns up to, but before the last column, then separately
indexing the last column. For the input features, we can select all rows and all columns except
the last one by specifying : for in the rows index, and :-1 in the columns index."""

X = [:, :-1]

In [ ]:
"""For the output column, we can select all rows again using : and index just the last column
by specifying the -1 index."""
y = [:, -1]

In [15]:
"""Putting all of this together, we can separate a 3-column 2D dataset into input and output
data as follows:"""
# split input and output data
from numpy import array
# define array
data = array([
[11, 22, 33],
[44, 55, 66],
[77, 88, 99]])
# separate data
X, y = data[:, :-1], data[:, -1]
print(X)
print("=====")
print(y)


[[11 22]
 [44 55]
 [77 88]]
=====
[33 66 99]


In [17]:
# split train and test data
from numpy import array
# define array
data = array([
[11, 22, 33],
[44, 55, 66],
[77, 88, 99]])
# separate data
split = 2
train,test = data[:split,:],data[split:,:]
print(train)
print("======================")
print(test)


[[11 22 33]
 [44 55 66]]
[[77 88 99]]


In [18]:
# Array Reshaping
# Data Shape
"""NumPy arrays have a shape attribute that returns a tuple of the length of each dimension of
the array. For example:
"""
# shape of one-dimensional array
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data.shape)



(5,)


In [19]:
# A tuple with two lengths is returned for a two-dimensional array.
# shape of a two-dimensional array
from numpy import array
# list of data
data = [[11, 22],
[33, 44],
[55, 66]]
# array of data
data = array(data)
print(data.shape) # Running the example returns a tuple with the number of rows and columns.


(3, 2)


In [21]:
# row and column shape of two-dimensional array
from numpy import array
# list of data
data = [[11, 22],
# Array Reshaping 31
[33, 44],
[55, 66]]
# array of data
data = array(data)
print('Rows: %d' % data.shape[0])
print('Cols: %d' % data.shape[1])

Rows: 3
Cols: 2


In [ ]:
# Reshape 1D to 2D Array
"""It is common to need to reshape a one-dimensional array into a two-dimensional array with
one column and multiple arrays. NumPy provides the reshape() function on the NumPy array
object that can be used to reshape the data. The reshape() function takes a single argument
that specifies the new shape of the array. In the case of reshaping a one-dimensional array into
a two-dimensional array with one column, the tuple would be the shape of the array as the first
dimension (data.shape[0]) and 1 for the second dimension."""
# Syntax
data = data.reshape((data.shape[0], 1))


In [22]:
# reshape 1D array to 2D
from numpy import array
# define array
data = array([11, 22, 33, 44, 55])
print(data.shape)
# reshape
"""Running the example prints the shape of the one-dimensional array, reshapes the array to
have 5 rows with 1 column, then prints this new shape."""
data = data.reshape((data.shape[0], 1))
print(data.shape)


(5,)
(5, 1)


In [ ]:
# Reshape 2D to 3D Array
# data.reshape((data.shape[0], data.shape[1], 1))

"""It is common to need to reshape two-dimensional data where each row represents a sequence
into a three-dimensional array for algorithms that expect multiple samples of one or more time
steps and one or more features. A good example is the LSTM recurrent neural network model
in the Keras deep learning library. The reshape function can be used directly, specifying the
new dimensionality. This is clear with an example where each sequence has multiple time steps
with one observation (feature) at each time step. We can use the sizes in the shape attribute on
the array to specify the number of samples (rows) and columns (time steps) and fix the number
of features at 1."""
# syntax
data.reshape((data.shape[0], data.shape[1], 1))

In [23]:
# reshape 2D array to 3D
from numpy import array
# list of data
data = [[11, 22],
[33, 44],
[55, 66]]
# array of data
data = array(data)
print(data.shape)
# reshape
"""Running the example first prints the size of each dimension in the 2D array, reshapes the
array, then summarizes the shape of the new 3D array.
"""
data = data.reshape((data.shape[0], data.shape[1], 1))
print(data.shape)

(3, 2)
(3, 2, 1)
