**Numpy**

    Definitions:
    
    NumPy, which stands for Numerical Python,is a library consisting of multidimensional array objects
    
    1 -mathematical and logical operations on arrays can be performed.
    2- developed by Jim Hugunin
    3- He has developed another package Numarray was also developed
    4- in 2005,Travis Oliphant created NumPy package by incorporating the features of Numarray into Numeric package
    
    
    Operations using NumPy:
    
    1- Mathematical and logical operations on arrays.
    2- Fourier transforms and routines for shape manipulation.
    3- NumPy has in-built functions for linear algebra and random number generation.
    
    Installion Guide :
    pip install numpy
    
    NumPy is an N-dimensional array type called ndarray
    
    syntax: numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)
    
    object : Any object exposing the array interface method returns an array, or any (nested) sequence.
    dtype  : Desired data type of array, optional
    copy   : Optional. By default (true), the object is copied
    order  : C (row major) or F (column major) or A (any) (default)
    subok  : By default, returned array forced to be a base class array. If true, sub-classes passed through
    ndmin  : Specifies minimum dimensions of resultant array
    
    

In [2]:
import numpy as np 
a = np.array([1,2,3]) 
a

array([1, 2, 3])

In [3]:
# more than one dimensions 
import numpy as np 
a = np.array([[1, 2], [3, 4]]) 
a

array([[1, 2],
       [3, 4]])

In [5]:
# minimum dimensions 
import numpy as np 
a = np.array([1, 2, 3,4,5], ndmin = 2) 
a

array([[[1, 2, 3, 4, 5]]])

In [8]:
# dtype parameter 
import numpy as np 
a = np.array([1, 2, 3], dtype = complex) 
a

array([ 1.+0.j,  2.+0.j,  3.+0.j])

###### Data type Object (dtype) in NumPy Python

    A data type object (an instance of numpy.dtype class) describes how the bytes in the fixed-size block of memory corresponding to an array item should be interpreted. It describes the following aspects of the data:

    1- Type of the data (integer, float, Python object, etc.)
    2- Size of the data (how many bytes is in e.g. the integer)
    3 - Byte order of the data (little-endian or big-endian)
    4- If the data type is structured, an aggregate of other data types, (e.g., describing an array item consisting of an integer and a float),
    5- what are the names of the “fields” of the structure, by which they can be accessed,
    6- what is the data-type of each field, and
    7- which part of the memory block each field takes.
    8- If the data type is a sub-array, what is its shape and data type.

In [12]:
# using array-scalar type 
import numpy as np 
dt = np.dtype(np.int32) 
dt

dtype('int32')

In [13]:
#int8, int16, int32, int64 can be replaced by equivalent string 'i1', 'i2','i4', etc. 
import numpy as np 

dt = np.dtype('i4')
dt 

dtype('int32')

In [14]:
# using endian notation 
import numpy as np 
dt = np.dtype('>i4') 
dt

dtype('>i4')

In [15]:
# first create structured data type 
import numpy as np 
dt = np.dtype([('age',np.int8)]) 
dt 

dtype([('age', 'i1')])

In [16]:
# now apply it to ndarray object 
import numpy as np 

dt = np.dtype([('age',np.int8)]) 
a = np.array([(10,),(20,),(30,)], dtype = dt) 
a

array([(10,), (20,), (30,)], 
      dtype=[('age', 'i1')])

In [17]:
# file name can be used to access content of age column 
import numpy as np 

dt = np.dtype([('age',np.int8)]) 
a = np.array([(10,),(20,),(30,)], dtype = dt) 
a['age']

array([10, 20, 30], dtype=int8)

In [18]:
import numpy as np 
student = np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')]) 
student

dtype([('name', 'S20'), ('age', 'i1'), ('marks', '<f4')])

In [19]:
import numpy as np 

student = np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')]) 
a = np.array([('abc', 21, 50),('xyz', 18, 75)], dtype = student) 
a

array([(b'abc', 21, 50.0), (b'xyz', 18, 75.0)], 
      dtype=[('name', 'S20'), ('age', 'i1'), ('marks', '<f4')])

In [10]:
# Python Program to create a data type object  
# containing a 32 bit big-endian integer 
import numpy as np 
  
# i4 represents integer of size 4 byte 
# > represents big-endian byte ordering and < represents little-endian encoding. 
# dt is a dtype object 
dt = np.dtype('>i4') 
  
print("Byte order is:",dt.byteorder) 
  
print("Size is:",dt.itemsize) 
  
print("Data type is:",dt.name) 

dt = np.dtype(np.int32)      # 32-bit integer
dt = np.dtype(np.complex128) # 128-bit complex floating-point number

Byte order is: >
Size is: 4
Data type is: int32


Each built-in data type has a character code that uniquely identifies it.

'b' − boolean

'i' − (signed) integer

'u' − unsigned integer

'f' − floating-point

'c' − complex-floating point

'm' − timedelta

'M' − datetime

'O' − (Python) objects

'S', 'a' − (byte-)string

'U' − Unicode

'V' − raw data (void)

###### NumPy - Array Attributes

In [20]:
# ndarray.shape
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 
a.shape

(2, 3)

In [21]:
# this resizes the ndarray 
import numpy as np 

a = np.array([[1,2,3],[4,5,6]]) 
a.shape = (3,2) 
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [22]:
# ndarray.ndim

# an array of evenly spaced numbers 
import numpy as np 
a = np.arange(24) 
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [23]:
# this is one dimensional array 
import numpy as np 
a = np.arange(24) 
a.ndim  

# now reshape it 
b = a.reshape(2,4,3) 
b 
# b is having three dimensions

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [24]:
## numpy.itemsize

# dtype of array is int8 (1 byte) 
import numpy as np 
x = np.array([1,2,3,4,5], dtype = np.int8) 
x.itemsize

1

In [25]:
# numpy.flags
# C_CONTIGUOUS (C) : The data is in a single, C-style contiguous segment
#  F_CONTIGUOUS (F) :The data is in a single, Fortran-style contiguous segment
#  OWNDATA (O)      : The array owns the memory it uses or borrows it from another object
#  WRITEABLE (W)    : The data area can be written to. Setting this to False locks the data, making it read-only
# ALIGNED (A)       : The data and all elements are aligned appropriately for the hardware
# UPDATEIFCOPY (U) : This array is a copy of some other array. When this array is deallocated, the base array will be updated with the contents of this array

import numpy as np 
x = np.array([1,2,3,4,5]) 
x.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

###### NumPy - Array Creation Routines
    numpy.empty(shape, dtype = float, order = 'C')
    
    Shape : Shape of an empty array in int or tuple of int
    Dtype  : Desired output data type. Optional
    Order : 'C' for C-style row-major array, 'F' for FORTRAN style column-major array
    

In [26]:
import numpy as np 
x = np.empty([3,2], dtype = int) 
x

array([[0, 0],
       [0, 0],
       [0, 0]])

In [27]:
# array of five zeros. Default dtype is float 
import numpy as np 
x = np.zeros(5) 
x

array([ 0.,  0.,  0.,  0.,  0.])

In [28]:
import numpy as np 
x = np.zeros((5,), dtype = np.int) 
x

array([0, 0, 0, 0, 0])

In [29]:
# custom type 
import numpy as np 
x = np.zeros((2,2), dtype = [('x', 'i4'), ('y', 'i4')])  
x

array([[(0, 0), (0, 0)],
       [(0, 0), (0, 0)]], 
      dtype=[('x', '<i4'), ('y', '<i4')])

In [31]:
# array of five ones. Default dtype is float 
import numpy as np 
x = np.ones(5) 
x

array([ 1.,  1.,  1.,  1.,  1.])

In [32]:
import numpy as np 
x = np.ones([2,2], dtype = int) 
x

array([[1, 1],
       [1, 1]])

###### NumPy - Array From Existing Data
    numpy.asarray:This routine is useful for converting Python sequence into ndarray.
    syntax: numpy.asarray(a, dtype = None, order = None)
    
    a= Input data in any form such as list, list of tuples, tuples, tuple of tuples or tuple of lists
    dtype =By default, the data type of input data is applied to the resultant ndarray
    order = C (row major) or F (column major). C is default
    

In [33]:
# convert list to ndarray 
import numpy as np 

x = [1,2,3] 
a = np.asarray(x) 
a

array([1, 2, 3])

In [34]:
# dtype is set 
import numpy as np 

x = [1,2,3]
a = np.asarray(x, dtype = float) 
a

array([ 1.,  2.,  3.])

In [35]:
# ndarray from tuple 
import numpy as np 

x = (1,2,3) 
a = np.asarray(x) 
a

array([1, 2, 3])

In [36]:
# ndarray from list of tuples 
import numpy as np 

x = [(1,2,3),(4,5)] 
a = np.asarray(x) 
a

array([(1, 2, 3), (4, 5)], dtype=object)