## Array creation

##### There are 6 general mechanisms for creating arrays:

* Conversion from other Python structures (i.e. lists and tuples)

* Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)

* Replicating, joining, or mutating existing arrays

* Reading arrays from disk, either from standard or custom formats

* Creating arrays from raw bytes through the use of strings or buffers

* Use of special library functions (e.g., random)

### Conversion from other Python structures (i.e. lists and tuples)

In [2]:
import numpy as np

In [3]:
lst = [1,2,4,7,8]

In [6]:
cre_arry= np.array(lst) # 1D array

In [7]:
cre_arry

array([1, 2, 4, 7, 8])

In [8]:
arry_2d= np.array([lst]) # 2D array

In [9]:
arry_2d

array([[1, 2, 4, 7, 8]])

In [10]:
arry_2d.size # check total number of elements in the ndarray

5

In [13]:
arry_2d.ndim # Check Dimension (axes) of the ndarray

2

In [15]:
arry_2d.dtype   # Check dtypes

dtype('int32')

In [16]:
arry_2d.shape  # check shape

(1, 5)

In [17]:
arry_2d.itemsize # itemsize returns the size (in bytes) of each element of a NumPy array.

4

In [22]:
my_array = np.array([ [1, 4, 5, 6], [7, 8, 9, 10], [11, 12, 14, 16] ],dtype=np.int32) # you can set int8, int16, float32,float64

In [23]:
my_array

array([[ 1,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 14, 16]])

In [25]:
tup=(2,5,6,7)

In [26]:
tup_arry= np.array(tup) # 1D array

In [27]:
tup_arry

array([2, 5, 6, 7])

In [28]:
tup_arry= np.array([tup]) # 2D array

In [29]:
tup_arry

array([[2, 5, 6, 7]])

### Intrinsic NumPy array creation functions

In [35]:
arrgne= np.arange(3)

In [36]:
arrgne

array([0, 1, 2])

In [37]:
arrgne= np.arange(3,10,dtype=np.float32) # 1D 

In [38]:
arrgne

array([3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [41]:
npline = np.linspace(2,2) # 1D

In [42]:
npline

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [43]:
arr_2d= np.eye(2) #Return a 2-D array with ones on the diagonal and zeros elsewhere.
arr_2d

array([[1., 0.],
       [0., 1.]])

In [46]:
arr_2d= np.diag([2,2,3,44,4]) ## 2D array diagonally represents
arr_2d

array([[ 2,  0,  0,  0,  0],
       [ 0,  2,  0,  0,  0],
       [ 0,  0,  3,  0,  0],
       [ 0,  0,  0, 44,  0],
       [ 0,  0,  0,  0,  4]])

### general ndarray creation functions¶

In [49]:
zeros= np.zeros((3,2)) # if you create zeros
zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [50]:
emp= np.empty((3,2)) # if you create zeros
emp

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [54]:
oness= np.ones((10,2))
oness

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [55]:
rad= np.random.rand(2,3)
rad

array([[0.14817425, 0.75659144, 0.23791602],
       [0.71797855, 0.01182494, 0.51333544]])

### Replicating, joining, or mutating existing arrays

In [57]:
a = np.array([1, 2, 3, 4, 5, 6])

In [58]:
b = a[:2]  ## Vector [0,1]
b

array([1, 2])

In [59]:
b += 1

In [60]:
b

array([2, 3])

In [61]:
b =a[:-1]
b

array([2, 3, 3, 4, 5])

In [62]:
b =a[-1:]
b

array([6])

### Reading arrays from disk, either from standard or custom formats¶

In [63]:
ldtxt = np.loadtxt('simple.csv', delimiter = ',', skiprows = 1) 

In [64]:
ldtxt

array([[0., 0.],
       [1., 1.],
       [2., 4.],
       [3., 9.]])

### Creating arrays from raw bytes through the use of strings or buffers

There are a variety of approaches one can use. If the file has a relatively simple format then one can write a simple I/O library and use the NumPy fromfile() function and .tofile() method to read and write NumPy arrays directly (mind your byteorder though!) If a good C or C++ library exists that read the data, one can wrap that library with a variety of techniques though that certainly is much more work and requires significantly more advanced knowledge to interface with C or C++.

### Use of special library functions (e.g., SciPy, Pandas, and OpenCV)

NumPy is the fundamental library for array containers in the Python Scientific Computing stack. Many Python libraries, including SciPy, Pandas, and OpenCV, use NumPy ndarrays as the common format for data exchange, These libraries can create, operate on, and work with NumPy arrays.