# broadcasting

__The term broadcasting refers to the ability of NumPy to treat arrays of different shapes during arithmetic operations. Arithmetic operations on arrays are usually done on corresponding elements. If two arrays are of exactly the same shape, then these operations are smoothly performed__

In [1]:
import numpy as np 

In [2]:
a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40]) 
c = a * b 

In [3]:
c

array([ 10,  40,  90, 160])

In [4]:
c = a - b 

In [5]:
c

array([ -9, -18, -27, -36])

In [6]:
c = a + b 

In [7]:
c

array([11, 22, 33, 44])

In [16]:
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0])  

In [17]:
a

array([[ 0.,  0.,  0.],
       [10., 10., 10.],
       [20., 20., 20.],
       [30., 30., 30.]])

In [18]:
b

array([1., 2., 3.])

In [19]:
a+b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [20]:
a-b

array([[-1., -2., -3.],
       [ 9.,  8.,  7.],
       [19., 18., 17.],
       [29., 28., 27.]])

#### numpy.ravel

* This function returns a flattened one-dimensional array. A copy is made only if needed. The returned array will have the same type as that of the input array. The function takes one parameter.

numpy.ravel(a, order)

In [21]:
a = np.arange(8).reshape(2,4) 

In [22]:
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [23]:
a.ravel() # convert to 1 D

array([0, 1, 2, 3, 4, 5, 6, 7])

In [24]:
a.flatten() # convert to 1 D

array([0, 1, 2, 3, 4, 5, 6, 7])

In [25]:
a.flatten(order = 'F') # The flattened array in F-style ordering

array([0, 4, 1, 5, 2, 6, 3, 7])

In [26]:
a.flat[5] # function returns a 1-D iterator over the array

5

In [27]:
a = np.arange(12).reshape(3,4) 

In [28]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
np.transpose(a)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])