### Single element indexing

In [1]:
import numpy as np

In [2]:
x = np.arange(10)

In [3]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
x = x[:]
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
x2 = x[1]
x2

1

In [6]:
x.shape = (2,5) # now x is 2-dimensional

In [7]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [10]:
x[1,3] ## start from 1 rows and 3 index

8

In [11]:
b = x>5

In [12]:
b

array([[False, False, False, False, False],
       [False,  True,  True,  True,  True]])

In [13]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [14]:
x[:,2:3]  # 2 D array all rows and all columns

array([[2],
       [7]])

In [19]:
x[:,:1]

array([[0],
       [5]])

#### this resizes the ndarray 

In [20]:
a = np.array([[1,2,3],[4,5,6]]) 
a.shape = (3,2) 
a

array([[1, 2],
       [3, 4],
       [5, 6]])

* Slicing can also include ellipsis (…) to make a selection tuple of the same length as the dimension of an array. If ellipsis is used at the row position, it will return an ndarray comprising of items in rows.

In [23]:
x = np.array([[1,2,3],[3,4,5],[4,5,6]]) 

In [24]:
x[...,1]  # The items in the second column are

array([2, 4, 5])

In [25]:
a[1,...] # The items in the second row are:

array([3, 4, 5])