##### NumPy - Indexing & Slicing

    Contents of ndarray object can be accessed and modified by indexing or slicing
    types of indexing methods are available − 
    
    1-field access 
    2-basic slicing 
    3-advanced indexing.

In [1]:
# start, stop, and step parameters to the built-in slice function
import numpy as np 
a = np.arange(10) 
s = slice(2,7,2) 
a[s]

array([2, 4, 6])

In [2]:
import numpy as np 
a = np.arange(10) 
b = a[2:7:2] 
b

array([2, 4, 6])

In [3]:
# slice single item 
import numpy as np 

a = np.arange(10) 
b = a[5] 
b

5

In [4]:
# slice items starting from index 
import numpy as np 
a = np.arange(10) 
a[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# slice items between indexes 
import numpy as np 
a = np.arange(10) 
a[2:5]

array([2, 3, 4])

In [8]:
import numpy as np 
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
a  

# slice items starting from index
print('Now we will slice the array from the index a[1:]' )
a[1:]

Now we will slice the array from the index a[1:]


array([[3, 4, 5],
       [4, 5, 6]])

##### advanced indexing − 

    1- Integer 
    2- Boolean.

In [9]:
import numpy as np 
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 
   
print('Our array is:') 
print(x) 
print('\n') 

rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]]) 
y = x[rows,cols] 
   
print('The corner elements of this array are:')
y

Our array is:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


The corner elements of this array are:


array([[ 0,  2],
       [ 9, 11]])

In [10]:
import numpy as np 
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 

print('Our array is:') 
print(x) 
print('\n')  

# slicing 
z = x[1:4,1:3] 

print('After slicing, our array becomes:')
print(z) 
print('\n')  

# using advanced index for column 
y = x[1:4,[1,2]] 

print('Slicing using advanced index for column:')
y

Our array is:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


After slicing, our array becomes:
[[ 4  5]
 [ 7  8]
 [10 11]]


Slicing using advanced index for column:


array([[ 4,  5],
       [ 7,  8],
       [10, 11]])

##### Boolean Array Indexing

In [11]:
import numpy as np 
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 

# Now we will print the items greater than 5 
print('The items greater than 5 are:' )
x[x > 5]

The items greater than 5 are:


array([ 6,  7,  8,  9, 10, 11])

In [15]:
# In this example, NaN (Not a Number) elements are omitted by using ~ (complement operator).
import numpy as np 
a = np.array([np.nan, 1,2,np.nan,3,4,5]) 
a[~np.isnan(a)]

array([1., 2., 3., 4., 5.])

##### NumPy - Broadcasting

        broadcasting refers to the ability of NumPy to treat arrays of different shapes during arithmetic operations. Arithmetic operations on arrays are usually done on corresponding elements. If two arrays are of exactly the same shape, then these operations are smoothly performed

In [16]:
import numpy as np 

a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40]) 
c = a * b 
c

array([ 10,  40,  90, 160])

In [17]:
d = a + b 
d

array([11, 22, 33, 44])

##### NumPy - Iterating Over Array
    
    NumPy package contains an iterator object numpy.nditer. It is an efficient multidimensional iterator object using which it is possible to iterate over an array.
    
    Let us create a 3X4 array using arange() function and iterate over it using nditer

In [20]:
import numpy as np
a = np.arange(0,60,5)
#a = a.reshape(3,4)

for x in np.nditer(a):
   print(x)

0
5
10
15
20
25
30
35
40
45
50
55


In [24]:
import numpy as np 
a = np.arange(0,60,5) 

print('Transpose of the original array is:')
b = a.T 
b 

for x in np.nditer(b): 
   print(x)

Transpose of the original array is:
0
5
10
15
20
25
30
35
40
45
50
55
