##### Slicing-Stacking arrays

In [3]:
import numpy as np

In [5]:
n =[6,7,8]

In [6]:
n[0:2]


[6, 7]

In [8]:
n[-1]

8

In [9]:
a =np.array([6,7,8])

In [10]:
a[0:2]

array([6, 7])

In [11]:
a[-1]

8

#### numpy.loadtxt

numpy.loadtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, converters=None, skiprows=0, usecols=None, unpack=False, ndmin=0, encoding='bytes', max_rows=None)[source]¶

In [4]:
a=np.array([[1,2,3],[4,5,6]])

In [5]:
np.savetxt("out.txt",a) 


In [6]:
y =np.loadtxt("out.txt")

In [7]:
y

array([[1., 2., 3.],
       [4., 5., 6.]])

In [9]:
b = np.asarray([ [1,2,3], [4,5,6], [7,8,9] ])
np.savetxt("foo.csv", b, delimiter=",")

In [10]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
from numpy import genfromtxt
my_data = genfromtxt('foo.csv', delimiter=',')

In [17]:
my_data

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])