### Numpy 1-d examples

In [ ]:
import numpy as np
a = np.array([1,2,3,4,5,6])
a

In [47]:
a[0]

1

In [48]:
a[2:]

array([3, 4, 5, 6])

In [ ]:
a.size

In [3]:
a.itemsize

4

In [4]:
a.ndim

1

In [5]:
a.dtype

dtype('int32')

In [9]:
a.argmax()

5

In [8]:
a.max()

6

In [10]:
a.min()

1

In [11]:
a.std()

1.707825127659933

In [12]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [13]:
a.mean()

3.5

In [21]:
b = a.reshape(2,3)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
b.ndim

2

In [26]:
c = np.array([1,2,3,4,5,6], dtype='complex')
c

array([ 1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j,  5.+0.j,  6.+0.j])

In [30]:
d = np.array([1,2,3,4,5,6], ndmin = 3)
d

array([[[1, 2, 3, 4, 5, 6]]])

In [25]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

### 2 -d Array Examples

In [31]:
x= np.array([[1,2],[2,4],[4,5]])
x

array([[1, 2],
       [2, 4],
       [4, 5]])

In [49]:
x[0][1]

2

In [55]:
x[2:,:]

array([[4, 5]])

In [32]:
x.ndim

2

In [33]:
x.shape

(3, 2)

### Broadcasting

In [35]:
x1= np.array([[1,2],[2,4],[4,5]])
x2= np.array([[1,2],[2,4],[4,5]])
Z= x1 * x2
Z

array([[ 1,  4],
       [ 4, 16],
       [16, 25]])

In [36]:
x1= np.array([[1,2],[2,4],[4,5]])
x2= np.array([[1,2],[2,4],[4,5]])
Z= x1 + x2
Z

array([[ 2,  4],
       [ 4,  8],
       [ 8, 10]])

### Data Types

In [37]:
# using array-scalar type 
import numpy as np 
dt = np.dtype(np.int32) 
dt

dtype('int32')

In [39]:
#int8, int16, int32, int64 can be replaced by equivalent string 'i1', 'i2','i4', etc. 
import numpy as np 
dt = np.dtype('i8')
dt

dtype('int64')

In [40]:
d = np.dtype(int)
d

dtype('int32')

In [41]:
y = np.zeros((2, 3))
y

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [43]:
z= np.ones((5,3))
z

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [57]:
data = np.arange(5)
data

array([0, 1, 2, 3, 4])

In [63]:
# start, stop, and step parameters to the built-in slice function
import numpy as np 
a3 = np.arange(10) 
a3
s = slice(2,7,2) # slice
a3[s]

array([2, 4, 6])

In [64]:
b3 = a3[2:7:2]  # index slicing 
b3

array([2, 4, 6])

In [58]:
for i in range(5):
    print(i)

0
1
2
3
4


In [59]:
# convert list to ndarray 
import numpy as np 

x = [1,2,3] 
a = np.asarray(x) 
a

array([1, 2, 3])

### indexing 

In [75]:
import numpy as np 
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 
print(x)
rows = np.array([[2,1],[3,3]])
cols = np.array([[0,2],[0,2]]) 
y = x[rows,cols]
print('The corner elements of this array are:')
y

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
The corner elements of this array are:


array([[ 6,  5],
       [ 9, 11]])

In [83]:
import numpy as np 
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 

# Now we will print the items greater than 5 
print('The items greater than 5 are:' )
x[x > 4].max()

The items greater than 5 are:


11

In [84]:
# NumPy - Iterating Over Array
import numpy as np
a = np.arange(0,60,5)
#a = a.reshape(3,4)

for x in np.nditer(a):
   print(x)

0
5
10
15
20
25
30
35
40
45
50
55
